### PR TITLE
Disabling and reducing log levels: too much logging, not suitable for…

### PR DESCRIPTION
**Pull request by mathieucarbou**
… high perf app doing a high rate of requests or websocket messages

### CODE REVIEW

**Comment by hoeken** [comment]
A couple issues here:

1. it seems the build/ folder was included here accidentally?
2. i'd rather comment out the log stuff rather than remove.

I'll go ahead and make these changes manually and close this PR

**Comment by mathieucarbou** [comment]
Oh boy! I saw that laster that `/build` was not in the `.gitignore`...

**Comment by mathieucarbou** [comment]
They are commented out already ;-)

**Comment by hoeken** [comment]
> They are commented out already ;-)

i misread the diff, i misread the ones where it was just a debug level switch.  implemented and pushed.

**Pull request closed without merging**
