### PR TITLE
Propose TemplatePrinter

### PR DESCRIPTION
**Pull request by Chris--A**
I have created a simple template processing tool. Primarily this has been built to work with `PsychicStreamResponse` proposed in #45. Incorporation directly into `PsychicStreamResponse` and other response types is possible. Implements some of #55. 

**This is not specific to PsychicHttp, and it works with any `Print` object. You could for example, template data out to `File`, `Serial`, etc...**.

The template engine is a `Print` interface and can be printed to directly, however,  if you are just templating a few short strings, I'd probably just use `response.printf()` instead. **Its benefit will be seen when templating large inputs such as files.**

One benefit may be **templating a **JSON** file avoiding the need to use ArduinoJson.**

Before closing the underlying `Print`/`Stream` that this writes to, it must be flushed as small amounts of data can be buffered. A convenience method to take care of this is shows in `example 3`.

The header file is not currently added to `PsychicHttp.h` and users will have to add it manually:

```C++
#include <TemplatePrinter.h>
```
 
## Template parameter definition:

- Must start and end with a preset delimiter, the default is `%`
- Can only contain `a-z`, `A-Z`, `0-9`, and `_`
- Maximum length of 63 characters (buffer is 64 including `null`).
- A parameter must not be zero length (not including delimiters).
- Spaces or any other character do not match as a parameter, and will be output as is.
- Valid examples
  - `%MY_PARAM%`
  - `%SOME1%`
- **Invalid** examples
  - `%MY PARAM%`
  - `%SOME1 %`
  - `%UNFINISHED`
  - `%%`

## Template processing
A function or lambda is used to receive the parameter replacement.

```C++
bool templateHandler(Print &output, const char *param){
  //...
}

[](Print &output, const char *param){
  //...
}
```

Parameters:
- `Print &output` - the underlying `Print`, print the results of templating to this.
- `const char *param` - a string containing the current parameter.

The handler must return a `bool`.
- `true`: the parameter was handled, continue as normal.
- `false`: the input detected as a parameter is not, print literal.

See output in **example 1** regarding the effects of returning `true` or `false`.

## Template input handler
This is not needed unless using the static convenience function `TemplatePrinter::start()`. See **example 3**.

```C++
bool inputHandler(TemplatePrinter &printer){
  //...
}

[](TemplatePrinter &printer){
  //...
}
```

Parameters:
- `TemplatePrinter &printer` - The template engine, print your template text to this for processing.

## Example 1 - Simple use with `PsychicStreamResponse`:
This example highlights its most basic usage.

```C++

//  Function to handle parameter requests.

bool templateHandler(Print &output, const char *param){

  if(strcmp(param, "FREE_HEAP") == 0){
    output.print((double)ESP.getFreeHeap() / 1024.0, 2);

  }else if(strcmp(param, "MIN_FREE_HEAP") == 0){
    output.print((double)ESP.getMinFreeHeap() / 1024.0, 2);

  }else if(strcmp(param, "MAX_ALLOC_HEAP") == 0){
    output.print((double)ESP.getMaxAllocHeap() / 1024.0, 2);
    
  }else if(strcmp(param, "HEAP_SIZE") == 0){
    output.print((double)ESP.getHeapSize() / 1024.0, 2);
  }else{
    return false;
  }
  output.print("Kb");
  return true;
}

//  Example serving a request
server.on("/template", [](PsychicRequest *request) {
  PsychicStreamResponse response(request, "text/plain");

  response.beginSend();
  
  TemplatePrinter printer(response, templateHandler);

  printer.println("My ESP has %FREE_HEAP% left. Its lifetime minimum heap is %MIN_FREE_HEAP%.");
  printer.println("The maximum allocation size is %MAX_ALLOC_HEAP%, and its total size is %HEAP_SIZE%.");
  printer.println("This is an unhandled parameter: %UNHANDLED_PARAM% and this is an invalid param %INVALID PARAM%.");
  printer.println("This line finished with %UNFIN");
  printer.flush();

  return response.endSend();
});   
```

The output for example looks like:
```
My ESP has 170.92Kb left. Its lifetime minimum heap is 169.83Kb.
The maximum allocation size is 107.99Kb, and its total size is 284.19Kb.
This is an unhandled parameter: %UNHANDLED_PARAM% and this is an invalid param %INVALID PARAM%.
This line finished with %UNFIN
```

## Example 2 - Templating a file

```C++
server.on("/home", [](PsychicRequest *request) {
  PsychicStreamResponse response(request, "text/html");
  File file = SD.open("/www/index.html");

  response.beginSend();

  TemplatePrinter printer(response, templateHandler);

  printer.copyFrom(file);
  printer.flush();
  file.close();

  return response.endSend();
}); 
```

## Example 3 - Using the `TemplatePrinter::start` method.
This static method allows an RAII approach, allowing you to template a stream, etc... without needing a `flush()`. The function call is laid out as:

```C++
TemplatePrinter::start(host_stream, template_handler, input_handler);
```

\*these examples use the `templateHandler` function defined in example 1.

### Serve a file like example 2
```C++
server.on("/home", [](PsychicRequest *request) {
  PsychicStreamResponse response(request, "text/html");
  File file = SD.open("/www/index.html");

  response.beginSend();
  TemplatePrinter::start(response, templateHandler, [&file](TemplatePrinter &printer){
    printer.copyFrom(file);
  });
  file.close();

  return response.endSend();
});
```

### Template a string like example 1
```C++
server.on("/template2", [](PsychicRequest *request) {

  PsychicStreamResponse response(request, "text/plain");

  response.beginSend();

  TemplatePrinter::start(response, templateHandler, [](TemplatePrinter &printer){
    printer.println("My ESP has %FREE_HEAP% left. Its lifetime minimum heap is %MIN_FREE_HEAP%.");
    printer.println("The maximum allocation size is %MAX_ALLOC_HEAP%, and its total size is %HEAP_SIZE%.");
    printer.println("This is an unhandled parameter: %UNHANDLED_PARAM% and this is an invalid param %INVALID PARAM%.");
  });

  return response.endSend();
});
```

### CODE REVIEW

**Comment by zekageri** [comment]
Long ago, with AsyncTCP we discussed that the template character should be changed to a more complex type.
% is commonly used in `CSS` and in `javascript` strings. I think it would be much more mature to use a multi character template delimeter like EJS (https://ejs.co/) or moustache (https://github.com/janl/mustache.js) does it.

- In the case of EJS: `<%= EJS %>`
- In the case of moustache: `{{mustache}}`

**Comment by Chris--A** [comment]
@zekageri 
I'm doing a bit of an investigation, but to avoid unnecessary work, are there any compelling reasons to actually change from the `%NAME%` format. Sure a `%` may be used inside the code itself, but it doesn't really present an issue.

My implementation is different to others I've seen (AsyncWeb...), and _**example 1**_ shows that unhandled matches get printed out, so unless you are explicitly match a parameter and return `true`, the text is passed through as is anyway.

Additionally, the delimiter can be changed to any other character, so you could do `#NAME#`, `$NAME$`, `~NAME~`.

I'm thinking it may be good to support a different prefix/suffix char so things like `<NAME>`, `{NAME}`,`[NAME]`, & `(P_NAME)` will work.

However, multi char prefixes and suffixes from what I can see will deliver little to no additional benefit.

**Comment by zekageri** [comment]
I can't recall what was the specific issue with async template but i will search for it asap. Maybe it was just broken from the start. I remember that if you had two classnames which both contained % char for a parameter the file broke. And there was a long discussion too. Will check!

**Comment by zekageri** [comment]
Here are the issues with one char templating

- https://github.com/me-no-dev/ESPAsyncWebServer/issues/300
- https://github.com/me-no-dev/ESPAsyncWebServer/issues/333
- https://github.com/me-no-dev/ESPAsyncWebServer/issues/644
- https://github.com/me-no-dev/ESPAsyncWebServer/issues/1234
- https://github.com/me-no-dev/ESPAsyncWebServer/issues/1249

Some comments

- https://github.com/me-no-dev/ESPAsyncWebServer/issues/300#issuecomment-1317987797
- https://github.com/me-no-dev/ESPAsyncWebServer/issues/300#issuecomment-1246735752

**Comment by Chris--A** [comment]
I have updated the code to ignore zero length parameters, not a harmful bug, but does not meet validity requirements.. Thank you @zekageri

**Comment by zekageri** [comment]
Well, it sounds like a whole lot better than Async's template parameter!
Thank you very much for your work, I will try it and hope @hoeken will merge it soon!

**Comment by Chris--A** [comment]
Yeah, lets do it. I was planning on allowing the size of the buffer (64 bytes) to be modifiable, but is a reasonable size. Not too short that complex parameter names can't be used, and not so long that it uses heaps of memory.

Certainly something I can look at if there is a compelling reason in the future.

**Comment by dzungpv** [comment]
@hoeken You should merge this, I am planing to replace ESPAsyncWebServer.

**Comment by hoeken** [comment]
Will do.

**Comment by hoeken** [comment]
Merged this as part of pull request by @dzungpv 

Thanks again for your contribution.

**Pull request merged**
