### PR TITLE
Fix memory leak when send headers in PsychicResponse

### PR DESCRIPTION
**Pull request by dzungpv**
I have merge https://github.com/hoeken/PsychicHttp/pull/56 and with other bug fixes and improvement:
- [Optional using https server in ESP IDF](https://github.com/dzungpv/PsychicHttp/commit/cebdbaeb765c96521d3233a1f2b30102c78b5c44)
- [Support using as ESP IDF component](https://github.com/dzungpv/PsychicHttp/commit/69542237e311de4a5dd998fcb695e0bb2ddee598)
- [Fix memory leak when send headers in PsychicResponse](https://github.com/dzungpv/PsychicHttp/commit/ec80969f28c032305a82d8e65783b84ebe4dcbed)

### CODE REVIEW

**Comment by hoeken** [comment]
Thank you very much for this PR.  Everything looks good, and it's definitely a step in the right direction for using this server within ESP-IDF.  As I'm not really too familiar with using ESP-IDF (which I really should learn).  If it's not too much trouble, would you mind creating a simple example project in examples/esp-idf.  I'm using github actions to automatically compile those and make sure that new commits don't break the existing code.

**Comment by dzungpv** [comment]
Yes I have finished it, but there is a problem with CI, you can try to fix it.

**Comment by hoeken** [comment]
Wow thanks!  This is a great start. I'll get this merged and try to fix the
CI stuff.

**Comment by dzungpv** [comment]
It is Github CI image problem. I can build it in my machine. ESP IDF quite complicate but when you are making work, it is great.

**Comment by hoeken** [comment]
I'm going to merge this now.  It looks like the CI stuff is failing on the LittleFS.  All I really want is to make sure that the library itself compiles with esp-idf I might slim down that example to just a simple hello world page if I can't get the CI to compile.  Thanks again for your work.

**Comment by Chris--A** [comment]
Hi @dzungpv & @hoeken,
It is highly inappropriate and disrespectful to your contributors to copy an existing commit and re submit under a different user. Regardless of attribution in the comment, my PR and commit was already there waiting for months to be entered.

**Comment by dzungpv** [comment]
> Hi @dzungpv & @hoeken, It is highly inappropriate and disrespectful to your contributors to copy an existing commit and re submit under a different user. Regardless of attribution in the comment, my PR and commit was already there waiting for months to be entered.

I merge your code to use internal, and create the PR after some modification , hoeken can merge your commit first and merge me. I have no control to the project. @hoeken can to redo it and make [Chris--A](https://github.com/Chris--A) more happy?

**Comment by dzungpv** [comment]
@hoeken because of this PR https://github.com/hoeken/PsychicHttp/pull/96, you can rebate the code, merged Chris--A code first and merge the #96

**Pull request merged**
