### PR TITLE
Esp-IDF CI

### PR DESCRIPTION
**Pull request by hoeken**
Wow that was a struggle, but we have integration tests for using PsychicHttp with esp-idf (v4.4 at least) as a component.

### CODE REVIEW

**Comment by hoeken** [comment]
@dzungpv my local esp-idf setup on my mac isn't working.  i messed with a ton of stuff to get the CI compilation working.  Let me know if it still works for you on your setup?

**Comment by dzungpv** [comment]
> @dzungpv my local esp-idf setup on my mac isn't working. i messed with a ton of stuff to get the CI compilation working. Let me know if it still works for you on your setup?

I am running on MacOS too, it is Intel base and M2 base Macbook Pro on Sonoma 4.4.1, do you follow the guide in ESP IDF site? You just follow my guide in the esp-idf example. Additional install ESP IDF 4.47 here: https://docs.espressif.com/projects/esp-idf/en/v4.4.7/esp32/get-started/index.html#setting-up-development-environment. After setup each time you want to build open terminal and enter the esp-idf example, run ./path to 4.4.7 idf/export.sh, after that you are fine.

**Comment by dzungpv** [comment]
Also you remove the path to the PsychicHttp lib itself in the [[CMakeLists.txt](https://github.com/hoeken/PsychicHttp/blob/master/CMakeLists.txt)](https://github.com/dzungpv/PsychicHttp/blob/2915498a53583a271dee3b8e66d77773fa8f1178/examples/esp-idf/CMakeLists.txt#L9), so it will failed

**Comment by hoeken** [comment]
I finally got it working and installed on my mac.  Some weird virtualenv issue.  Its compiling fine for me now.

When I was scratching my head trying to get it to work, I changed that part based on what i saw from the LittleFS example.  I can try and change it back and see if it still works.

```set(EXTRA_COMPONENT_DIRS "../../")```

**Comment by dzungpv** [comment]
> I finally got it working and installed on my mac. Some weird virtualenv issue. Its compiling fine for me now.
> 
> When I was scratching my head trying to get it to work, I changed that part based on what i saw from the LittleFS example. I can try and change it back and see if it still works.
> 
> `set(EXTRA_COMPONENT_DIRS "../../")`

Yes, even on the Mac it can build but failed with Ubuntu CI. Great work on the CI, I take nearly an hour and could not make it working, and let the last part for you.

**Comment by hoeken** [comment]
Teamwork :)

**Pull request merged**
