### PR TITLE
captive portal added in main.cpp PsychicHttp example

### PR DESCRIPTION
**Pull request by 06GitHub**
Thanks for the great job done on PsychicHttp 👍 

**1) SUMMARY**

For my project, there is a need for **captive portal**, ie web page which opens automatically when user connects Wifi network (eg "PsychitHttp").

Captiveportal is implemented in **ESPAsyncWebServer** [https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/CaptivePortal/CaptivePortal.ino](url) and in **arduino-esp32 examples** [https://github.com/espressif/arduino-esp32/blob/master/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino](url)

This feature can be implemented with Psychichttp with a **dedicated handler, as shown in updated "main.cpp" example**.

If needed, captive portal could be added in "main.cpp" PsychicHttp example.

Thanks

Code is added below for reference.

**2) CODE**

**Definitions**
```
// captiveportal
// credits https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/CaptivePortal/CaptivePortal.ino
//https://github.com/espressif/arduino-esp32/blob/master/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino
#include <DNSServer.h> 
DNSServer dnsServer;            
//PsychicWebHandler captiverequest;
class CaptiveRequestHandler : public PsychicWebHandler { // handler 
public:
  CaptiveRequestHandler() {};
  virtual ~CaptiveRequestHandler() {};
  bool canHandle(PsychicRequest*request){
    // ... if needed some tests ... return(false);
    return true;  // activate captive portal
  }
  esp_err_t handleRequest(PsychicRequest *request) {   
   //PsychicFileResponse response(request, LittleFS, "/captiveportal.html"); // captive portal page, if any
   //return response.send();                                                 // return captive portal page
   return request->reply(200,"text/html","Welcome to captive portal !");  // simple text, comment if captive portal page
  }
};
CaptiveRequestHandler *captivehandler=NULL;             // handler for captive portal
```

**setup()**
```
    // captive portal
    dnsServer.start(53, "*", WiFi.softAPIP());                    // DNS requests are executed over port 53 (standard)     
    captivehandler= new CaptiveRequestHandler();                 // create captive portal handler, important : after server.on since handlers are triggered on a first created/first trigerred basis
    server.addHandler(captivehandler);                           // captive portal handler (last handler) 
```

**loop()**
` dnsServer.processNextRequest();       // captive portal`

**result (web page opened automatically)**
captiveportal

### CODE REVIEW

**Comment by hitecSmartHome** [comment]
Captive portal already works

**Comment by woodenplastic** [comment]
server.on("/redirect", HTTP_GET, [](PsychicRequest* request)
    { return request->redirect(redirectURL); });

  server.on("/connecttest.txt", HTTP_GET, [](PsychicRequest* request)
    { return request->redirect(redirectURL); });

  server.on("/hotspot-detect.html", HTTP_GET, [](PsychicRequest* request)
    { return request->redirect(redirectURL); });

  server.on("/generate_204", HTTP_GET, [](PsychicRequest* request)
    {
      return request->redirect(redirectURL); });

  server.on("/gen_204", HTTP_GET, [](PsychicRequest* request)
    { return request->redirect(redirectURL); });
    
    
    i do it like this. any better versions?

**Comment by hitecSmartHome** [comment]
```cpp
server.addHandler(&firstBootHandler).setFilter(ON_AP_FILTER);
```

```cpp
class FirstBootHandler : public PsychicWebHandler{
    public:
        esp_err_t handleRequest(PsychicRequest *request) override;
};
inline FirstBootHandler firstBootHandler;
```

```cpp
esp_err_t FirstBootHandler::handleRequest(PsychicRequest *request){
   request->loadBody();
   request->loadParams();
   if (request->path() == "/something") {
       // handle "/something"
   }else if (request->path() == "/something1") {
       // handle "/something1"
   }else{
       // hanle "/"
   }
}
```

**Comment by hoeken** [comment]
I'm happy to merge these changes, but would you mind removing the captive portal code from the main demo code and adding it as a separate sketch/program with a simple "Hello World" page?  The main example is getting pretty complex as it is.  Similar to how your OTA example is its own separate sketch.

**Comment by 06GitHub** [comment]
Ok, I agree with you, let's keep the main example as it is.

So I will update/resubmit PR and include 2 examples "captive portal" and "OTA update" as separate examples. I will do this in the coming days.

Will add them in the Arduino section since I am using Arduino IDE.

Maybe it could be worth to describe each example as a separate directory, as in https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer/examples ? Today there is one example for PlatformIO, one for Arduino and one for ESP-IDF, so it is not "easy" to add new examples.

Thanks !

**Comment by hoeken** [comment]
Just name them arduino_ota and arduino_captive_portal for now, I'll see
about shuffling things around later.

**Pull request closed without merging**
