### PR TITLE
Defer Endpoint registering after server start

### PR DESCRIPTION
**Pull request by mathieucarbou**
This change allows to register endpoints before server startup and they will be registered once server is started.

### CODE REVIEW

**Comment by hoeken** [comment]
I like this, but I think we can accomplish the same thing with less work once we get the framework for request processing pulled into PsychicHttp itself.

I'm going to implement that and then lets circle back to this.

**Comment by proddy** [comment]
Also consider https://github.com/hoeken/PsychicHttp/issues/35 to get the order of things right

**Comment by mathieucarbou** [comment]
> I like this, but I think we can accomplish the same thing with less work once we get the framework for request processing pulled into PsychicHttp itself.
> 
> I'm going to implement that and then lets circle back to this.

completely agree!

this was an extraction of what I use at the moment to test a migration path from ESPAsyncWS

**Comment by mathieucarbou** [comment]
> Also consider #35 to get the order of things right

yes that's what is discussed in the discord: right now, we cannot to a sequence of start / stop / start / stop like we can do with ESPASyncWS with begin / end / begin / end...

**Comment by hoeken** [comment]
With the new request processing changes, we aren't adding endpoints directly to the esp-idf server, instead the endpoints just get added to that server._endpoints list.  The exception to that is websocket handlers, which need to be a unique endpoint as there is code we can't replicate in PsychicHttp for that.

So, the changes to PsychicEndpoint are probably redundant.

It would be a good idea to add the removeEndpoint() function which can remove the endpoint from the list.  This function should also check endpoint->handler()->isWebsocket() and remove the endpoint config from server._esp_idf_endpoints as well as call httpd_unregister_uri_handler

Also, is there a way to change this PR to point to the v2 dev branch?

**Comment by mathieucarbou** [comment]
Yes I will refresh them.

**Pull request closed without merging**
